name: Track Commits to SQLite

on:
  push:
    branches:
      - main

jobs:
  log_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history for git show

      - name: Extract commit info and update database
        run: |
          set -e

          DB="commits_log.sqlite"
          SHA=$(git rev-parse HEAD)
          AUTHOR=$(git log -1 --format="%an")
          EMAIL=$(git log -1 --format="%ae")
          DATE=$(git log -1 --format="%ad" --date=iso)
          FILES=$(git show --pretty="" --name-only $SHA | paste -sd ";" -)

          echo "Files changed: $FILES"

          sqlite3 "$DB" "CREATE TABLE IF NOT EXISTS commits (
            sha TEXT PRIMARY KEY,
            author TEXT,
            email TEXT,
            timestamp TEXT,
            files TEXT
          );"

          if [ -z "$FILES" ]; then
            echo "No files changed — skipping insert."
            exit 0
          fi

          sqlite3 "$DB" "REPLACE INTO commits
            (sha, author, email, timestamp, files)
            VALUES (
              '$SHA',
              '$AUTHOR',
              '$EMAIL',
              '$DATE',
              '$FILES'
            );"

      - name: Commit updated SQLite file
        run: |
          git config user.name "auto-tracker"
          git config user.email "tracker@yourorg.com"
          git add commits_log.sqlite
          git diff --cached --quiet || git commit -m "Auto-update commit tracker: $SHA"
          git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
